language: bash
servics: docker

env:
  - IMAGE_LATEST: certhub/certhub:rolling-lego
  - DOCKER_USERNAME: certhubci
  - secure: "Fb7oSkmTuKWHtyL/t6//K1VnAGzMgfpzUIGoGtFkIgnq/Ufs5lgQDG5z6S/0jfU9xknX8wCvON1Bgip0xlcxZteeMbHfJguVy3Dva0KZ298yjTGeNFTIu9hd90zyiqAYXcX4g4dOluT8BwWD9DrvyTk7QHBdP8yef6whaQSBKjuUEupl1+UF7zfTzpx/9fFHkQvnInjeVuZHbnFSYac/F6SESMG0kZD3R0CR4NHpT5N9ouHLxpMneeqAPaI/xiRSTA008DnvYHj0AQQslOR/kUJY2gdBK4KKSJw45mUKiFHrrdcBk7atNoUVu6KJXuABl//lN7wRghi8MLDyjwzSmNCKSv4EWzJHjcIj8xbOxl8eQRUZB9/3UqD9sfUW636OSVzEa0OfSQ7fN5t6abBcc/Fu7l5Z6IU4qrl6nrSczeYN7d3mVsL+H+BxlDWzndfvSkN8cEgNp5t/5SnwHDYQCf0gu+pq89qptZcZvsFnb51m53tzRAEKMnrtT/4UYhAK5R2XvEJeXlknN25+4Tmn0rJ1fvOjB67kHUAGPusxnU7sEi7inqEvMp8z1NAIK8G6mhB+hnCRH1UY/+SKM9Eu8ALNlq4YZ+VHX15hN8zk3OhmwrBIBsv9j45A19bZgq3Wvez6AXFn1uA3XKx3Ww1c/d3B29jyhwtF3bsWj0LUn5Y="

before_script:
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker pull $IMAGE_LATEST || true
  - docker build --cache-from $IMAGE_LATEST --tag $IMAGE_LATEST .
  - docker push $IMAGE_LATEST
