---
os: linux
dist: focal
language: shell
services: docker

env:
  global:
    - IMAGE_NAME: certhub/certhub
    - IMAGE_VARIANT: lego
    - IMAGE_BUILD_ID: "${IMAGE_VARIANT}-travis-build-${TRAVIS_BUILD_ID}"
    - DOCKER_USERNAME: certhubci
    # travis encrypt DOCKER_PASSWORD=abcdefg[...]
    - secure: "Fb7oSkmTuKWHtyL/t6//K1VnAGzMgfpzUIGoGtFkIgnq/Ufs5lgQDG5z6S/0jfU9xknX8wCvON1Bgip0xlcxZteeMbHfJguVy3Dva0KZ298yjTGeNFTIu9hd90zyiqAYXcX4g4dOluT8BwWD9DrvyTk7QHBdP8yef6whaQSBKjuUEupl1+UF7zfTzpx/9fFHkQvnInjeVuZHbnFSYac/F6SESMG0kZD3R0CR4NHpT5N9ouHLxpMneeqAPaI/xiRSTA008DnvYHj0AQQslOR/kUJY2gdBK4KKSJw45mUKiFHrrdcBk7atNoUVu6KJXuABl//lN7wRghi8MLDyjwzSmNCKSv4EWzJHjcIj8xbOxl8eQRUZB9/3UqD9sfUW636OSVzEa0OfSQ7fN5t6abBcc/Fu7l5Z6IU4qrl6nrSczeYN7d3mVsL+H+BxlDWzndfvSkN8cEgNp5t/5SnwHDYQCf0gu+pq89qptZcZvsFnb51m53tzRAEKMnrtT/4UYhAK5R2XvEJeXlknN25+4Tmn0rJ1fvOjB67kHUAGPusxnU7sEi7inqEvMp8z1NAIK8G6mhB+hnCRH1UY/+SKM9Eu8ALNlq4YZ+VHX15hN8zk3OhmwrBIBsv9j45A19bZgq3Wvez6AXFn1uA3XKx3Ww1c/d3B29jyhwtF3bsWj0LUn5Y="
    # travis encrypt PRIVATE_SSH_KEY=$(printf %q "$(</path/to/ssh/private.key)")
    - secure: "JoOh62PL7HN0hZbM8S5fBP2RBnRNxxVGx7qeb1mJR9Ees2YqdyuAO7a+bTD+z6ZZJGfKRCrH1tiBE9rXzc4Gy7tGfPPniTqmIBPwSGSCDWQdwFePuTUo07oy+/Gywn+40PgSU7dMGuMx9jckeKXci5g5vAYzE4ixMVq6HsujDZLqRF/HWFvNFqwBA1WmtX+7u6MDzDntNYSusKt0GLo9JexnctTD7GYL3O+FDMP6jYptasAJnHRKaB+LqxxlrrdbizZpO0BrXvS4GXgTpuJPEZIp9S/pdqfYL6opcjAcJbmOJU3yA1vzo1SWMRcsB5q8BPeyix73JFutwrjOuDpiaGf7UqFskbVEgRGJd9anw0OIVXTvgBdYjYPZPvMX4tI1i96h5UhJa+TYedROVMeTFcGNNZZ300mtszg/ZJ3dFIGTBXa0U1aP4IOTxfqAcfgWZd4+g7JeTc4w3ZQQ4FWx5zEDQC6FL1Z4WChCSEUyHpyw7/TlzjrnWqeI8kqKQ1EMmw0p7xFWkhNXNoZEkH2LFG20EvdAY3nB+8EWSWZWwXUOEadFiP/DICkTecqMIKz0yRuLHc9RlAyPB+PblHRmY7oMm3Fmn6emG3qX3+NOiqGJYMQNxP7MbA1dRBBQjy+sgIq7kafSVR9RdFMa9LXsGDyTV+pob2iw0i44mqDQIO8="
    # travis encrypt PRIVATE_DIGITALOCEAN_TOKEN=abcdefg[...]
    - secure: "J6sPFbhw+XV0yWergsSCzfkzPQK6jd5iz+q0kihdaDJ4fwe2+FyEqwUUpjvJpKjTLsY/8LCuizY3KtH4MGR3gSgL2ByxGbzmMOhbLy3mqn1USwG47Zw9h4LCIZ8yXhelxj8GAvtfsUAVjuZW7QmqtmkUYXYtji46xChxdTNl6/WA5TpKvgpoMh2QI/yoOB5IcP1mbX0qaG03XL4Wit9YfP9tDp/tXQk5qcYyqvZT+cL3y82WGLCwbRNG6M6e3kzs+YXoUYQqgkRAHmmJk6Ph+ZOOyZxDia1BsrihBfr6kcRUU16kiJ9BhaLcalayUms2pV9SSN6dMBiiwsgJ3bJtfKc438lHByDEGRjiWafVzs3yirwcViVqtMAg1Wr7CGfEhZjBn2QWIkVvWUBRtPiV0nTW86/AMy66fySEyApdx8Vx9Bg0jIiDLEI0akYmBM+m10ipF/E00iW3gTuaaP7qZa6zm1dk+VablgoD+XiV26hfVcAQne59PmeAT9KZPo9pnEfT2LpceI6eCZ3GzT5+DD0+v1ckzo2mQ2dxfxVKfYKrRm0JdA/aR1SnTMEbnsB2C9d9ZxTH8kmkQZipy9u4Wp4OXkBRy8sNB55V4uYxHItHqPyCGJUFSMTmMfANqjV2qLtmvDbV6OQajhcyjo6q36czL5E2C0s6sliVMcNxEjY="
    # travis encrypt GH_TOKEN=abcdefg[...]
    - secure: "BqfX4meHQZDjSeCYjylrn/bXYjo/Nmn6sWplfdA+5LKbtE337pdM1nwMW84r7fcsPfL564VUInSXQV3lHWcxXUFRUrcOtASk80+tZkcpYevTzTUfVZ7UeKUshwZYptFX+thFfVXmo51Kso7iuzmQFinSnMZJGjHAfGw3poT14nGRq79yr7zu+uBg660gYAwAd6wf9PinxARQstZdPFykgQ6VAipvMW4EzghQ5FKxbjOJwN+UZQVAiAqpY6nPosdSdRt4GWYBnHfkgwe2g3avPu6RX4gvhjBa6eqHg26Q9fshn+bvfY3pxK1iJD1omaurlztOHWYKrS7nSLepIQ+VnBN1wk9xyeMVDk7fYmd0VlbhqCKlZrhd43hCpTaj6KmxWVyEPtv6hPoUISUioD3YHydWnV3Yt68Agh6DDZjTyS+OVm0PGUJwTrnn/IoKRVavXD69vyr3L6TKS7UQckV+mmlyhXseS9TfkAymscvGLslyfa741dm/w+r+/do8NP/wLIIUCLm4CAn7ugbLCeULJRbD+t0Q9c/+IM4BIK68F+iw/W36uwMAFEwqauXXkRJQ/mkRpwpvGtVDvClBNzbteKV8xf6SFOEdsgaMJYHY4+8xOZsh06n1gT2NQ8mopcZ0u9Dnp5shYdHCnTp8Se6MxxMaI1cWUgMHojnZsSmcXCw="
    # travis encrypt PRIVATE_LEGO_ACCOUNT_KEY=$(printf %q "$(</path/to/.lego/accounts/acme-staging-v02.api.letsencrypt.org/travis-ci@certhub.io/keys/travis-ci@certhub.io.key)")
    - secure: "ZwSUCwyOXz7zTbGz7wMQfB+nGZd6IOiLdk2BmvLwvZ/fbijqNhKffrVy/IOQYTIGkGR+QM2EEnYWcBndtjJzDp+2LwRVc184c6CcbhahKxzscNrKTjFasxQn7fIZfFyrxMzGEKQ30kiVyTUzd7uuGUrcd8n8381aAd+QuaeovFdmu3uxp58wh+zj8WfFUhTVPeXWNTjEDfPa/AtZjM6ERbnfBZRZPdCcgcsWxrzatJcmaaNbUj5vIVGjm3teiujhKsoyp08uElhqLyDDRkQ3dnwVmlhJw/riWlIfW3azCMkE12IXT11IhxzvmmUWr0+Xv93JLJ3FQjUYzEoVc9gWgpDbK0IBEzgs/qxqb8d4+ppPAgdjdUpoGdodmE+hIQT9QKW/YsvqGRMoI1igLK7H9JQCmN7xLJ/xtmt69JrOAocxgQOae5nFCAjWNOBCI0keMPerJrRtQoXaul0OUe9BbN10sfsPeLm3yKtVGpGXbKzD5pgiVKpLnZmpQSlvNd2dOIk9KMsaAH2REZKxYV1Ui6vKi3bkOKzhluQWfzT8sEwe1bd5OWWh3l4V2CQh6h31WOXnrTyRKn4LssTba6hGG9Bg0OmjVHCl70NVW4stO6yh1N7EO3e6XucLil52fSS7PhDU0jiKGTFMqRnxcdniv7j1yFdpNnwwaK0uCffcH7k="

stages:
  - name: Build
  - name: Integration test
  - name: Dockerhub rolling
    if: branch = develop AND type IN (push, cron)
  - name: Github release
    if: branch = latest AND type = push
  - name: Dockerhub release
    if: tag IS present

before_script:
  - docker --version
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

jobs:
  include:
    - stage: Build
      script:
        - >
            docker build
            --tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
            --build-arg build_log_label="Travis CI Build #${TRAVIS_BUILD_NUMBER}"
            --build-arg build_log_url="${TRAVIS_BUILD_WEB_URL}"
            .
        - docker push "${IMAGE_NAME}:${IMAGE_BUILD_ID}"

    - stage: Integration test
      env:
        - DOCKER_COMPOSE_ARGS: >
            "
            -f integration-test/docker-compose.yml
            -f integration-test/docker-compose.travis.yml
            -f integration-test/docker-compose.test-${IMAGE_VARIANT}.travis.yml
            "
      script:
        - docker-compose ${DOCKER_COMPOSE_ARGS} build
        - docker-compose ${DOCKER_COMPOSE_ARGS} run sut

    - stage: Dockerhub rolling
      script:
        - docker pull "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-rolling"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-rolling"

    - stage: Github release
      script:
        - nvm install lts/*
        - npx semantic-release

    - stage: Dockerhub release
      script:
        - export VERSION_PATCH="${TRAVIS_TAG#v}"
        - export VERSION_MINOR="${VERSION_PATCH%.*}"
        - export VERSION_MAJOR="${VERSION_MINOR%.*}"
        - docker pull "${IMAGE_NAME}:${IMAGE_BUILD_ID}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_PATCH}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MINOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MAJOR}"
        - docker tag "${IMAGE_NAME}:${IMAGE_BUILD_ID}" "${IMAGE_NAME}:${IMAGE_VARIANT}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_PATCH}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MINOR}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}-${VERSION_MAJOR}"
        - docker push "${IMAGE_NAME}:${IMAGE_VARIANT}"
