version: "3.4"

services:
    sut:
        command: /test/test-lego.sh
        environment:
          CERTHUB_LEGO_ARGS: >-
            --accept-tos
            --email travis-ci@certhub.io
            --server https://acme-staging-v02.api.letsencrypt.org/directory"
          CERTHUB_LEGO_CHALLENGE_ARGS: >-
            --dns digitalocean
          DO_AUTH_TOKEN: >-
            ${PRIVATE_DIGITALOCEAN_TOKEN}

    config:
        command: /test/config-setup-lego.sh
